version: '3.8'

services:
  google-scrapper-headless:
    build:
      context: .
      dockerfile: Dockerfile_headless
    ports:
      - "5394:5394"
    networks:
      - google-scrapper-net

networks:
  google-scrapper-net:
    driver: bridge